version: "3.5"
services:
    lint:
        image: lint
        build:
            context: .
            dockerfile: Dockerfile.cibuild
        entrypoint:
        - script/lint
    test:
        image: test
        build:
            context: .
            dockerfile: Dockerfile.cibuild
        entrypoint:
        - script/test
    test-build:
        image: test-build
        build:
            context: .
            dockerfile: Dockerfile.cibuild
        entrypoint:
        - script/test-build
